language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
sudo: false

env:
    global:
    matrix:
        - CONTAO_VERSION=~3.2
        - CONTAO_VERSION=~3.3

install:
    - composer require contao/core $CONTAO_VERSION --prefer-dist --dev
    - composer install --prefer-dist --dev

script: ant -keep-going
